### ISSUE TITLE
Trakt todo-list (help welcomed)

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#313]
- [x] introduce trakt.tv module
- [x] rewrite trakt provider (trakttv.js file) to use trakt.tv module instead (maintenance made easy)
- [ ] make trakttv.js a butter-provider
- [x] decide wheter localStorage is fitting (~~or use nedb like old implementation~~)
- [ ] display "episode" item instead of entire show
- [ ] fix the details (or remove the possibility of going to details at all)

https://github.com/butterproject/butter-desktop/commit/1417c20127db16c266772f526f1ad1eca7009dce

This commit rewrites entirely the watchlist and introduces the 'trakt.tv' package. 

There's a long list of things to do to have a proper trakt implementation. 

But first: @xaiki if everything needs to be rewritten, wouldn't it be a good time to split from core? Please assist on this matter.

**Comment by YIFYtorrents** [comment]
who is behind trakt.tv. Don't get me wrong but can it be trusted?

**Comment by vankasteelj** [comment]
It's a business runned by 3 guys I think.

**Comment by xaiki** [comment]
https://github.com/butterproviders/butter-provider-trakt-watchlist
so part of the work is done here, it still lacks proper testing.

**Comment by vankasteelj** [comment]
@xaiki it's only the watchlist though, not the entire trakt provider

**Comment by xaiki** [comment]
sure, we'd need to split out from core, i'd say use localStorage.
